import React from 'react';
import { Info, FileCheck } from 'lucide-react';

export interface RegulatoryDisclaimerProps {
  category?: string;
  variant?: 'compact' | 'full' | 'banner';
  className?: string;
}

export const RegulatoryDisclaimer: React.FC<RegulatoryDisclaimerProps> = ({
  category = 'general',
  variant = 'compact',
  className = '',
}) => {
  const fullNoticeText =
    "Platform Notice: Doorstep transactions record digital weight verification, commercial settlement, and chain-of-custody transfer for internal auditing and circular waste diversion accounting.";

  if (variant === 'banner') {
    return (
      <div className={`bg-emerald-50 dark:bg-emerald-950/40 border-l-4 border-emerald-500 p-4 rounded-r-lg shadow-sm ${className}`}>
        <div className="flex items-start gap-3">
          <Info className="w-5 h-5 text-emerald-600 dark:text-emerald-400 mt-0.5 shrink-0" />
          <div>
            <h4 className="text-sm font-semibold text-emerald-900 dark:text-emerald-200">
              Platform Transaction Disclaimer
            </h4>
            <p className="text-xs text-emerald-800 dark:text-emerald-300 mt-1 leading-relaxed">
              {fullNoticeText}
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (variant === 'compact') {
    return (
      <div className={`bg-slate-50 dark:bg-zinc-900/60 border border-slate-200 dark:border-zinc-800 rounded-lg p-3 ${className}`}>
        <div className="flex items-center gap-1.5 text-slate-700 dark:text-zinc-300 font-semibold text-xs mb-1">
          <Info className="w-4 h-4 text-emerald-600" />
          <span>Platform Record Note</span>
        </div>
        <p className="text-[11px] text-slate-500 dark:text-zinc-400 leading-snug">
          Platform logs track verified mass & digital chain-of-custody for commercial transaction settlement and audit trails.
        </p>
      </div>
    );
  }

  return (
    <div className={`bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl p-5 shadow-sm space-y-3 ${className}`}>
      <div className="flex items-center gap-2 border-b border-slate-100 dark:border-zinc-800 pb-3">
        <FileCheck className="w-5 h-5 text-emerald-600" />
        <h3 className="font-semibold text-slate-900 dark:text-zinc-100 text-sm">
          Platform Waste Sale Record Protocol
        </h3>
      </div>
      
      <div className="space-y-2 text-xs text-slate-600 dark:text-zinc-400">
        <p className="leading-relaxed">
          <strong className="text-slate-800 dark:text-zinc-200">1. Verification Record:</strong> Doorstep transaction records generated by Recyvia represent OTP-verified records of doorstep transaction and mass transfer.
        </p>
        <p className="leading-relaxed">
          <strong className="text-slate-800 dark:text-zinc-200">2. Statutory Status:</strong> This document is a platform-generated record for commercial and internal accounting and is not a government or CPCB statutory certificate.
        </p>
      </div>
    </div>
  );
};
